apiVersion: apps/v1
kind: Deployment
metadata:
  name: audioextractor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audioextractor
  template:
    metadata:
      labels:
        app: audioextractor
    spec:
      containers:
      - name: audioextractor
        image: javierenrique00/audioextractor-js:1.0.1
        resources:
        ports:
        - containerPort: 2000
---
apiVersion: v1
kind: Service
metadata:
  name: audioextractor
spec:
  selector:
    app: audioextractor
  ports:
  - port: 2000
    targetPort: 2000
  type: LoadBalancer
